"""
Streamlit web UI for Car Coach.
Run with: streamlit run streamlit_app.py

v1.5 — Web search is the SOURCE OF TRUTH. The model reads from search results only.
Parts are never generated by the model — they come from search results.
"""

import streamlit as st
import json
import os
import sys
import re
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from model_loader import chat
from profiles.loader import load_car_profile, format_car_context
from memory.build_memory import BuildMemory
from search.web_search import WebSearch

st.set_page_config(page_title="Car Coach", page_icon="🚗", layout="wide")

PROJECT_ROOT = Path(__file__).parent
MEMORY_FILE = PROJECT_ROOT / "memory" / "build_memory.json"

CORRECTION_KEYWORDS = ["redo", "wrong", "not it", "nope", "no that's not", "not what I wanted"]

def is_correction(text: str) -> bool:
    return any(kw in text.lower().strip() for kw in CORRECTION_KEYWORDS)

# =====================
# Sidebar
# =====================
with st.sidebar:
    st.title("🚗 Car Coach")
    st.divider()

    car = load_car_profile()
    if car:
        st.success(f"Loaded: {car.get('year')} {car.get('make')} {car.get('model')}")
        with st.expander("View car details"):
            for key, value in car.items():
                if key not in ["notes", "currentMods"]:
                    st.text(f"{key}: {value}")
            if car.get("currentMods"):
                st.markdown("**Current Mods:**")
                for mod in car["currentMods"]:
                    st.markdown(f"  • {mod}")
    else:
        st.warning("No car profile loaded")
        st.caption("Create profiles/my_car.json")

    st.divider()

    st.subheader("Correction Mode")
    correction_mode = st.toggle("Enable correction mode", value=True)
    if correction_mode:
        st.caption("Say 'wrong', 'redo', etc. to refine answers")

    st.divider()

    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()

    st.caption("v1.5 — Search-first, model reads from results only")

# =====================
# Session state
# =====================
if "messages" not in st.session_state:
    st.session_state.messages = []

if "memory" not in st.session_state:
    st.session_state.memory = BuildMemory(str(MEMORY_FILE))

if "awaiting_correction" not in st.session_state:
    st.session_state.awaiting_correction = False

if "search_results_cache" not in st.session_state:
    st.session_state.search_results_cache = ""

# =====================
# System prompt — model is a translator, not a source of parts
# =====================
SYSTEM_PROMPT = """You are Car Coach, a helpful assistant that explains car modifications clearly.

IMPORTANT: You do NOT generate part names yourself. Your job is to read the web search results provided below and summarize them for the user.

The user's car: {CAR_CONTEXT}

Your task:
- Read the "Available Parts" section below
- Explain what each part does in plain language
- Tell the user why it fits their specific car (based on the car profile)
- Warn about any risks for high-mileage or stock engines
- Use bullet points and keep it conversational

Rules:
1. ONLY talk about parts that appear in the "Available Parts" section
2. Do NOT invent, guess, or add any part not in the search results
3. If the search results don't have enough information, say "The search didn't return enough results for me to give confident recommendations."
4. If the user asks about something outside the search results, say "I don't have that in my search results — try asking something more specific."
5. Be practical and direct. No fluff.

How to format your response:
- Start with a brief intro (1 sentence)
- List the parts from the search results with what they do and price range
- End with a "What's next" section about build order
- If you're not confident about something, say so

Example response format:
"Based on what I found for your [year] [make] [model]:

• [Part name] — $[price] — [what it does and why it fits the user's car]

These are confirmed real parts from the search results. I verified them for your specific vehicle.

What's next: [build order advice]"
"""

def build_messages_search_first(car_context: str, search_results: str, correction: str = "") -> list:
    """Build messages where search results are the source of truth."""
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.append({"role": "system", "content": f"User's car:\n{car_context}"})
    messages.append({"role": "system", "content": f"Available Parts (ONLY use these — do NOT mention parts not in this list):\n\n{search_results}"})

    memory_text = st.session_state.memory.format_memory()
    if memory_text != "No build history yet.":
        messages.append({"role": "system", "content": f"Build history:\n{memory_text}"})

    if correction:
        messages.append({"role": "system", "content": f"User feedback on my previous answer: '{correction}'. Give a better answer using ONLY the parts from the Available Parts section above. Do NOT repeat the same approach."})

    for msg in st.session_state.messages:
        role = "assistant" if msg["role"] == "assistant" else "user"
        messages.append({"role": role, "content": msg["content"]})

    return messages

def get_response(messages: list) -> str:
    try:
        response = chat(messages)
        response = response.replace("<think>", "").replace("[/think]", "").strip()
        return response
    except Exception as e:
        return f"Error: {e}"

# =====================
# Chat UI
# =====================
st.title("Car Coach")

if not st.session_state.messages:
    car = load_car_profile()
    if car:
        welcome = f"Loaded your {car.get('year')} {car.get('make')} {car.get('model')} {car.get('trim', '')}. What do you want to work on today?"
        st.session_state.messages.append({"role": "assistant", "content": welcome})
    else:
        st.session_state.messages.append({
            "role": "assistant",
            "content": "Hey! I'm Car Coach. Create a `profiles/my_car.json` file to tell me about your ride, then let's get building."
        })

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

user_input = st.chat_input("Ask about your build...")

if user_input:
    car = load_car_profile()
    car_context = format_car_context(car)

    is_corr = is_correction(user_input) and correction_mode

    if st.session_state.awaiting_correction:
        correction = user_input
        st.session_state.awaiting_correction = False

        if st.session_state.messages and st.session_state.messages[-1]["role"] == "assistant":
            st.session_state.messages.pop()

        # Retry using cached search results
        cached = st.session_state.search_results_cache
        if cached:
            messages = build_messages_search_first(car_context, cached, correction)
            with st.chat_message("user"):
                st.markdown(f"[Retrying with feedback: {correction}]")
            with st.chat_message("assistant"):
                with st.spinner("Retrying..."):
                    response = get_response(messages)
                st.markdown(response)
            st.session_state.messages.append({"role": "assistant", "content": response})
        else:
            # No cached results — need to search again
            st.session_state.messages.append({"role": "user", "content": user_input})
            with st.chat_message("user"):
                st.markdown(user_input)
            with st.chat_message("assistant"):
                st.markdown("I don't have search results from your last question to compare against. Let me search again with your feedback...")
                st.session_state.awaiting_correction = True

        st.rerun()

    elif is_corr:
        st.session_state.awaiting_correction = True
        st.session_state.messages.append({"role": "user", "content": user_input})

        with st.chat_message("user"):
            st.markdown(user_input)

        with st.chat_message("assistant"):
            st.markdown("Sorry! What was wrong with it? What did you actually want?")

        st.rerun()

    else:
        st.session_state.awaiting_correction = False
        st.session_state.messages.append({"role": "user", "content": user_input})
        with st.chat_message("user"):
            st.markdown(user_input)

        # Step 1: Always search first
        with st.spinner("Searching the web for real parts..."):
            web_search = WebSearch()
            results = web_search.search(user_input, car or {})

        # Check if search actually returned results
        if not results or "[Web search failed]" in results or len(results) < 50:
            no_results_msg = "I couldn't find any search results for that query. This might be too specific or too broad. Try a simpler question like 'cold air intake for 2014 dodge durango 3.6l' or 'best tune for 2014 durango v6'."
            with st.chat_message("assistant"):
                st.markdown(no_results_msg)
            st.session_state.messages.append({"role": "assistant", "content": no_results_msg})
            st.session_state.search_results_cache = ""
        else:
            # Cache the results for correction mode
            st.session_state.search_results_cache = results

            # Step 2: Build messages with search results as the ONLY source
            messages = build_messages_search_first(car_context, results)

            with st.chat_message("assistant"):
                with st.spinner("Reading search results..."):
                    response = get_response(messages)

                # Final safety check — if model mentioned a part NOT in search results, flag it
                response_lines = response.split("\n")
                safe_lines = []
                for line in response_lines:
                    # If line contains a bullet point, check if it came from search results
                    if line.strip().startswith("•") or line.strip().startswith("-"):
                        # Extract potential part name
                        bullet_text = re.sub(r"^[-•]\s*", "", line.strip())
                        part_base = re.split(r"\s*[-—$]", bullet_text)[0].strip()
                        # Check if this part exists in search results
                        if part_base and part_base.lower() not in results.lower() and len(part_base) > 5:
                            # Part not in search results — flag it but don't show it
                            continue  # Skip this line entirely
                    safe_lines.append(line)

                safe_response = "\n".join(safe_lines)

                # Check if response is suspiciously short (model may have hallucinated beyond search)
                if len(safe_response) < 50:
                    safe_response = "The search results didn't have enough information for me to give confident recommendations. Try being more specific — for example, ask 'cold air intake for 2014 dodge durango 3.6l' instead of just 'intake'."

                st.markdown(safe_response)

            st.session_state.messages.append({"role": "assistant", "content": safe_response})
            st.session_state.memory.update_from_text(safe_response)

        st.rerun()